name: Playwright Tests
on:
  push:
    branches: [ main, master ] # This workflow triggers on push to main and master branches
  pull_request_target:
    types: [opened, synchronize, reopened] # And on pull request events to these branches
  schedule:
    - cron: '0 7 * * *' # Also, it triggers every day at 7 AM as per the cron schedule
jobs:
  test:
    timeout-minutes: 60 # The job is allowed to run for a maximum of 60 minutes
    runs-on: ubuntu-latest # It will run on the latest version of Ubuntu available
    steps:
      - uses: actions/checkout@v3 # Checks out a copy of your repository on the Ubuntu machine

      - uses: actions/setup-node@v3 # Sets up Node.js environment
        with:
          node-version: 16 # Specific Node.js version to use

      - name: Install dependencies
        run: npm ci # Install Node.js dependencies defined in package-lock.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps # Install required browsers with Playwright

      - name: Run Playwright tests
        run: npx playwright test # Run Playwright tests

      - name: Upload HTML report
        uses: actions/upload-artifact@v2 # Uploads the test report as an artifact
        with:
          name: playwright-report
          path: playwright-report/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Deploy the test report to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN for authentication
          publish_dir: ./playwright-report # Directory to deploy
          publish_branch: gh-pages # Branch to deploy to
